### ISSUE TITLE
Stride in Window class is unintutive?

### ISSUE THREAD

**Issue by amueller** [TheDatumOrg/TSB-AD#1]
Hey! I know this is an early version but I was wondering what the meaning of the ``stride`` in the ``Window`` class is. I'm not sure if it's used in this work; it seems not to be the stride with which the windowing is applied, but instead the stride of how each window is sampled from the series. Was that the intention?

**Comment by qhliu26** [comment]
Hi Andreas, thanks for your interest in our project! There are two parameters in the `Window` class: (i) `window` is used to specify the size of the sliding window, (ii) `stride` is the interval of each sliding window. We have an example use of Window [here](https://github.com/TheDatumOrg/TSB-AD/blob/main/TSB_AD/models/AE.py). Feel free to ask questions and make suggestions!

**Comment by amueller** [comment]
ok I guess stride is then working as intended. From the name I would have thought it would be the stride with which the window is moving forward, not the stride of sampling inside the window.
