### ISSUE TITLE
Maybe a Bug or My Misunderstanding

### ISSUE THREAD

**Issue by ProEcho1** [TheDatumOrg/TSB-AD#21]
Hello,  

Thank you for your previous response and for kindly reminding me about the release of the codes and datasets.

Recently, while running the benchmark, I noticed something in the 318th line of `model_wrapper.py` related to performing anomaly detection with AnomalyTransformer. Specifically, the parameter `output_c` was not explicitly set, causing it to default to a value of 1. While this does not lead to any errors due to PyTorch's broadcasting mechanism when calculating the MSE loss for tensors with different dimensions, it seems like it might introduce potential inconsistencies or unintended behavior.  

Upon reviewing the original repository of [AnomalyTransformer](https://github.com/thuml/Anomaly-Transformer), I found that both `input_c` and `output_c` were defined as the same value for the reconstruction loss calculation. This raised a question: are there any advantages to set like this, or could it be a small bug?  

I’d greatly appreciate your insights into this. Thank you for your time and effort ^_^!

**Comment by qhliu26** [comment]
Hi, 

Thank you for pointing that out! This is indeed an issue in our implementation (it’s not ideal to use inconsistent values for input_c and output_c during the calculation of reconstruction error). I’ve fixed this by ensuring that `output_c` now matches `input_c`. We’ll also update the evaluation results related to this issue on our online [leaderboard](https://thedatumorg.github.io/TSB-AD/). Let me know if you have any further questions or suggestions—your feedback is much appreciated!

**Comment by ProEcho1** [comment]
> Hi,
> 
> Thank you for pointing that out! This is indeed an issue in our implementation (it’s not ideal to use inconsistent values for input_c and output_c during the calculation of reconstruction error). I’ve fixed this by ensuring that `output_c` now matches `input_c`. We’ll also update the evaluation results related to this issue on our online [leaderboard](https://thedatumorg.github.io/TSB-AD/). Let me know if you have any further questions or suggestions—your feedback is much appreciated!

Thanks a lot!
