### ISSUE TITLE
congratulations! 

### ISSUE THREAD

**Issue by BraudoCC** [TheDatumOrg/TSB-AD#3]
Congratulations on your highly successful work. I would like to inquire about the following:
(1) When can we expect to see this paper?
(2) How can I use this repository to reproduce the benchmark results? Or, how can I batch call these datasets, as I noticed that some datasets have a label column labeled "label," others have "anomaly score," and some do not have a label column at all.
(3) Some deep learning-based methods have a multitude of hyperparameters. In their respective papers, even different datasets may require different parameters (such as hidden size). How are these hyperparameters standardized when conducting benchmarks?

**Comment by BraudoCC** [comment]
I notice the file VisionAnomaly/datasets/TSB-AD/File-List, sorry for my question (2). lol.

**Comment by qhliu26** [comment]
Hey! Thanks for your interest in our work. We will release the final version of the paper and datasets around the camera-ready day (at the end of this month) to address reviewers' comments. Thanks for your patience. Stay tuned🍻

**Comment by BraudoCC** [comment]
您好，我已收到您的邮件，我会在看到邮件内容后第一时间处理，祝您生活愉快！

**Comment by qhliu26** [comment]
The paper and dataset are now available at https://thedatumorg.github.io/TSB-AD.
