### ISSUE TITLE
Congratulations and Data Available

### ISSUE THREAD

**Issue by ProEcho1** [TheDatumOrg/TSB-AD#5]
Dear Authors,

Thank you for your insightful work! I would like to ask about the availability of the data: when I click the link in the 'Dataset' folder to access more time series data, it shows that permission is required before accessing the data. Could you please let me know whether I need to apply for this permission, or would you be able to share this part directly?

Thank you again for your comprehensive work; your response will be of great help to me ^_^.

Looking forward to your reply!

**Comment by qhliu26** [comment]
Hello! Thank you for your interest in our work. We're fixing some license issues related to the dataset, and we will try to make it publicly accessible with the appropiate license within the next week. Thank you for your patience, and we welcome any suggestions you may have!

**Comment by qhliu26** [comment]
The paper and dataset are now available at https://thedatumorg.github.io/TSB-AD.
